name: Derivatives SDK Tests

on:
    pull_request:
        branches:
        - main
        - master
    workflow_dispatch:
        inputs:
            environment:
                type: choice
                options:
                - "/production/001"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: amberdata/cicd@checkout_v4.1.6

    - name: Set up Python
      uses: amberdata/actions-setup-python@v3
      with:
          python-version: 3.10

    - name: Run unit tests
      run: python3 -m unittest -v tests/*.py
