name: Derivatives SDK Tests

on:
    schedule:
      - cron: "*/30 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install deprecation python-dotenv requests jsonschema

    - name: Run unit tests
      run: python3 -m unittest -v tests/*.py

    - name: Notify Slack on failure
      if: failure()
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data "{\"text\":\"Unit tests failed for ${GITHUB_REPOSITORY}. Please check the details.\", \"username\": \"CI Bot\", \"icon_emoji\": \":robot_face:\"}" \
        ${{ secrets.SDK_SLACK_WEBHOOK }}

    - name: Notify Opsgenie on failure
      if: failure()
      uses: cdqag/opsgenie-create-alert@v1
      with:
        apiKey: ${{ secrets.OPSGENIE_API_KEY }}
        message: "Derivatives SDK unit tests failed, see run #${{ github.run_number }} for details."
