name: Derivatives SDK Tests

on:
    pull_request:
        branches:
        - main
        - master

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install deprecation python-dotenv requests jsonschema

    - name: Run unit tests
      run: python3 -m unittest -v tests/*.py
