name: Run Tests

on:
    push:


jobs:
    build:
        runs-on: self-hosted
        name: Run Tests
    
        steps:
            - name: Checkout Repository
              uses: amberdata/actions-checkout@v3

            - name: Set up Python
              uses: amberdata/actions-setup-python@v3
              with:
                python-version: 3.10

            - name: Run unit tests
              run: |
                python3 -m unittest -v tests/*.py
