name: Derivatives SDK Tests

on:
    pull_request:
        branches:
        - main
        - master

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install deprecation python-dotenv requests jsonschema

    - name: Run unit tests
      run: python3 -m unittest -v tests/*.py


    - name: Notify Opsgenie on failure
      if: failure()
      run: |
        curl -X POST -H "Content-Type: application/json" \
        -H "Authorization: GenieKey ${{
        secrets.OPSGENIE_API_KEY }}" \
        -d '{
            "message": "Unit tests failed for the repository ${GITHUB_REPOSITORY} on branch ${GITHUB_REF}",
            "alias": "unit-test-failure",
            "description": "Unit tests failed for the repository ${GITHUB_REPOSITORY} on branch ${GITHUB_REF}. Please check the details.",
            "priority": "P3"
        }' \
        https://api.opsgenie.com/v2/alerts
