name: Derivatives SDK Tests

on:
    pull_request:
        branches:
        - main
        - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: amberdata/cicd@checkout_v4.1.6
      
    - name: Set up Python
      uses: amberdata/cicd@setup-python_v4.7.0

    - name: Run unit tests
      run: python3 -m unittest -v tests/*.py
